# This conda environment includes everything needed to build and use FABM-OS.
name: fabmos
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - cmake
  - fortran-compiler
  - pip
  - pygetm>=0.9.3
  - scipy
  - h5py
