# This conda environment includes everything needed to build and use FABM-OS on Windows.
name: fabmos
channels:
  - conda-forge
  - bolding-bruggeman
dependencies:
  - python>=3.8
  - cmake
  - m2w64-toolchain
  - pip
  - pygetm>=0.9.2
  - scipy
  - h5py
